id: I866B40D4
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-11T13:13:28.116019'
last_modified: '2022-06-11T13:13:28.116025'
parser: null
source_metadata:
  title: Tulku Thondup
  language: bo
  description: 'Texts by and about Tulku Thondup (sprul sku don grub, b. 1939):'
  volume:
    fADD4:
      title: Prayer for the Long Life of Tulku Thondup Rinpoche
      base_file: fADD4.txt
      order: 1
      parent: Long Life Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
